{% set name = "hangar" %}
{% set version = "0.5.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8e962dc51462a664c062f82df35c41612495ac4e431392fca7a4db6fc569e08b

build:
  number: 0
  skip: true  # [py<=35]
  entry_points:
    - hangar = hangar.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"


requirements:
  build:
    - {{ compiler('c') }}
    - cython >=0.27
  host:
    - pip
    - python
    - setuptools >=40.0
    - wheel >=0.30
  run:
    - click
    - grpcio
    - h5py >=2.9
    - hdf5plugin >=2.0
    - numpy
    - protobuf
    - python
    - python-blosc
    - python-lmdb >=0.92
    - python-xxhash
    - tqdm
    - wrapt

test:
  imports:
    - hangar
    - hangar.diagnostics
    - hangar.records
    - hangar.remote
    - hangar.backends
    - hangar.columns
  commands:
    - hangar --help
    - hangar --version

about:
  home: https://github.com/tensorwerk/hangar-py
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Hangar is version control for tensor data. Commit, branch, merge, revert, and collaborate in the data-defined software era.
  doc_url: https://hangar-py.readthedocs.io/
  dev_url: https://github.com/tensorwerk/hangar-py
  description: |
    Hangar is based off the belief that too much time is spent collecting, managing,
    and creating home-brewed version control systems for data. At it's core Hangar
    is designed to solve many of the same problems faced by traditional code version
    control system (ie. ``Git``), just adapted for numerical data.

extra:
  recipe-maintainers:
    - rlizzo
    - lantiga
