{% set name = "hangar" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d452f37b9ba063bbb1b888b8d251d41dd36cd830b4e710ee7aecf0d527ed90f5

build:
  number: 2
  skip: true  # [py<=35]
  entry_points:
    - hangar = hangar.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - wheel
    - cython >=0.27
  run:
    - click
    - grpcio
    - h5py >=2.9
    - hdf5plugin >=2.0
    - numpy
    - protobuf
    - python
    - python-blosc
    - python-lmdb >=0.92
    - python-xxhash
    - tqdm
    - wrapt

test:
  imports:
    - hangar
    - hangar.diagnostics
    - hangar.records
    - hangar.remote
    - hangar.backends
    - hangar.columns
  commands:
    - hangar --help
    - hangar --version

about:
  home: https://github.com/tensorwerk/hangar-py
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Hangar is version control for tensor data. Commit, branch, merge, revert, and collaborate in the data-defined software era.
  doc_url: https://hangar-py.readthedocs.io/
  dev_url: https://github.com/tensorwerk/hangar-py
  description: |
    Hangar is based off the belief that too much time is spent collecting, managing,
    and creating home-brewed version control systems for data. At it's core Hangar
    is designed to solve many of the same problems faced by traditional code version
    control system (ie. ``Git``), just adapted for numerical data.

extra:
  recipe-maintainers:
    - rlizzo
    - lantiga
