travis:
  secure:
    BINSTAR_TOKEN: Dw7emg3lxFiAqEOS6dccjUKwg6VeS8xc4wrWsi2W68BafsT9x81AEOO8lErqjL9MQ/hb8EddiwnKKy9OtsbQ6ewBs6eDJXyTXXfA3DpaWAaklsinbyrebtxysP+SHJlM/TYxviywG2bB64Vlpeh4HYisQ/izsdxNrG5uoxB9WOiqCf7yt042Z/KfXb6wcFu6SBQ4Jbh4hN09n/gpWaHPUYqX8u9WFDGoXGNsJ5rSPnsGzzj2TywCsodbDYgZKydonPdX16OIa68zHekzoqoRHu4efRuXLVxb9aREZeSLB+ZX/FH29GGV4UCGQxqsKB5CapHjgVBuUI6ufB4zIXzfxtp2KbvywXjdq7DzTYganF/zhzX45NS8T/YR3W0iuXEZpjwP+lP4ViFoGipsujUsaEMI9uoHYs8tAt4FwxeRvjKOUds2Nbd1ZfUGbUDwWIH74GajSrNL2QtN9KIpOwr54yP/JLS+3EJA4HEQ6PA7PSYnrQ8LKA8gZsNZu+PaGsXl/cJ34Y6Q5VTTjB+DBurbFRxS9aYFxg6ZdhMQ/JRQ1kW1PcokVCFHzO4lzBFsLo1qAhH6WenQ+P9kI8unfRzMMklVKcS+GTbTNrMPsJeoYLfKnpc2MC/+vO8g4ARnUkoEBOnmasdNoXKAclQQ+7uwJZyQDSv3rylhn1bxob9u1yo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
